spring.application.name=backend
server.port=8081
spring.data.mongodb.uri=mongodb+srv://juanmanalvarez_db_user:Admin2008@clustermodulo3.n85igzv.mongodb.net/Modulo3Ejemplo1?retryWrites=true&w=majority&appName=ClusterModulo3
